//! RageTrade-style treasury yield distribution.
//!
//! Token holders stake their tokens to earn a proportional share of treasury
//! yield generated by protocol fees. The distribution uses a global
//! **accumulator** that tracks cumulative yield per staked token, so claims
//! settle in real-time against the user's current stake.
//!
//! # Model
//!
//! - **Accumulator-based.** A global [`DistributionState::accumulator`] tracks
//!   cumulative yield per staked token, scaled by [`PRECISION`]. When yield is
//!   distributed, the accumulator increases by
//!   `amount * PRECISION / total_staked`.
//! - **Per-user checkpoint.** Each user stores the accumulator value at their
//!   last interaction (stake / unstake / claim). Pending yield is
//!   `staked * (accumulator - checkpoint) / PRECISION`, plus whatever an
//!   earlier stake size had already accrued ([`UserDistribution::pending`]).
//! - **Real-time claiming.** Users can claim their accumulated yield at any
//!   time; the claim transfers the pending yield immediately and updates the
//!   checkpoint.
//! - **Proportional to holdings.** The more tokens a user stakes, the larger
//!   their share of every distribution.
//! - **Two tokens.** Users stake the treasury's own asset ([`DataKey::Token`]);
//!   yield is paid out in the token handed to [`initialize`].
//! - **No double-counting.** Yield accrued against a stake size is settled into
//!   `pending` before that stake changes (and on every claim), so the same
//!   accumulator range is never priced twice and a changed position never
//!   forfeits what it already earned.
//!
//! # Invariant
//!
//! `total_claimed <= total_distributed` always holds: each claim transfers
//! `staked * (accumulator_delta) / PRECISION`, and the accumulator only moves
//! when yield is distributed, so the sum of all claims can never exceed the
//! sum of all distributions.

use soroban_sdk::{contractevent, contracttype, token, Address, Env};

use crate::{bump_ttl, DataKey, Error};

/// Scaling factor for the accumulator. An accumulator value of `PRECISION`
/// means one unit of yield per staked token has been distributed.
pub const PRECISION: i128 = 1_000_000_000; // 1e9

/// Global distribution state.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DistributionState {
    /// Cumulative yield per staked token, scaled by [`PRECISION`].
    pub accumulator: i128,
    /// Total yield distributed across all calls, cumulatively.
    pub total_distributed: i128,
    /// Total tokens currently staked.
    pub total_staked: i128,
    /// Unix timestamp of the last accumulator update.
    pub last_update: u64,
}

/// Per-user distribution state.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserDistribution {
    /// Tokens currently staked by the user.
    pub staked: i128,
    /// The accumulator value at the user's last interaction.
    pub checkpoint: i128,
    /// Total yield claimed by the user, cumulatively.
    pub claimed: i128,
    /// Yield accrued while staked at a *previous* stake size, settled here on
    /// every stake / unstake so a changed position never forfeits it.
    ///
    /// The accumulator is global, so pending yield is `staked * accumulator_delta`.
    /// Re-pricing that product against a new `staked` would either drop the
    /// shortfall or double-count the excess, so the settled portion is carried
    /// separately until it is claimed.
    pub pending: i128,
}

// ── Events ─────────────────────────────────────────────────────────────────

/// Emitted when yield is distributed to stakers.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct YieldDistributedEvent {
    #[topic]
    pub token: Address,
    /// Amount of yield tokens distributed.
    pub amount: i128,
    /// The accumulator value after the distribution.
    pub accumulator: i128,
    /// Total staked tokens at the time of distribution.
    pub total_staked: i128,
}

/// Emitted when a user claims accumulated yield.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct YieldClaimedEvent {
    #[topic]
    pub user: Address,
    /// Amount of yield tokens claimed.
    pub amount: i128,
    /// Cumulative amount claimed by this user after the call.
    pub total_claimed: i128,
}

/// Emitted when a user stakes tokens.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StakedEvent {
    #[topic]
    pub user: Address,
    /// Amount staked.
    pub amount: i128,
    /// Total staked tokens after the call.
    pub total_staked: i128,
}

/// Emitted when a user unstakes tokens.
#[contractevent]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UnstakedEvent {
    #[topic]
    pub user: Address,
    /// Amount unstaked.
    pub amount: i128,
    /// Total staked tokens after the call.
    pub total_staked: i128,
}

// ── Storage helpers ────────────────────────────────────────────────────────

fn config_token(env: &Env) -> Result<Address, Error> {
    env.storage()
        .instance()
        .get(&DataKey::DistributionConfig)
        .ok_or(Error::DistributionNotInitialized)
}

fn state(env: &Env) -> Result<DistributionState, Error> {
    env.storage()
        .instance()
        .get(&DataKey::DistributionState)
        .ok_or(Error::DistributionNotInitialized)
}

/// The token stakers deposit into the distribution: the treasury's own asset
/// (`DataKey::Token`), which is distinct from the yield token paid out on
/// claim.
fn holding_token(env: &Env) -> Result<Address, Error> {
    env.storage()
        .instance()
        .get(&DataKey::Token)
        .ok_or(Error::NotInitialized)
}

fn save_state(env: &Env, state: &DistributionState) {
    env.storage()
        .instance()
        .set(&DataKey::DistributionState, state);
}

fn user_distribution(env: &Env, user: &Address) -> Option<UserDistribution> {
    env.storage()
        .persistent()
        .get(&DataKey::UserDistribution(user.clone()))
}

fn save_user_distribution(env: &Env, user: &Address, dist: &UserDistribution) {
    let key = DataKey::UserDistribution(user.clone());
    env.storage().persistent().set(&key, dist);
    bump_ttl(env, &key);
}

// ── Core logic ─────────────────────────────────────────────────────────────

/// Pending yield for a user, in yield-token smallest units.
///
/// `staked * (accumulator - checkpoint) / PRECISION`, saturating at zero.
fn pending_yield_internal(
    state: &DistributionState,
    user: &UserDistribution,
) -> Result<i128, Error> {
    if user.staked <= 0 || state.accumulator <= user.checkpoint {
        return Ok(0);
    }
    let diff = state
        .accumulator
        .checked_sub(user.checkpoint)
        .ok_or(Error::MathOverflow)?;
    let pending = user.staked.checked_mul(diff).ok_or(Error::MathOverflow)? / PRECISION;
    Ok(pending)
}

/// Move yield accrued against the *current* stake into the user's carried
/// `pending` bucket and re-anchor their checkpoint, so the stake size can
/// change without re-pricing yield that has already been earned.
fn settle(user_dist: &mut UserDistribution, state: &DistributionState) -> Result<(), Error> {
    user_dist.pending = user_dist
        .pending
        .checked_add(pending_yield_internal(state, user_dist)?)
        .ok_or(Error::MathOverflow)?;
    user_dist.checkpoint = state.accumulator;
    Ok(())
}

/// Total claimable yield: the settled bucket plus whatever has accrued against
/// the current stake since the user's last interaction.
fn claimable(state: &DistributionState, user_dist: &UserDistribution) -> Result<i128, Error> {
    user_dist
        .pending
        .checked_add(pending_yield_internal(state, user_dist)?)
        .ok_or(Error::MathOverflow)
}

// ── Admin entry-point bodies ───────────────────────────────────────────────

/// Initialize the yield distribution. Admin only.
///
/// Sets the yield token and creates the initial distribution state. Must be
/// called before any other distribution function.
pub fn initialize(env: &Env, token: Address) -> Result<(), Error> {
    if env.storage().instance().has(&DataKey::DistributionConfig) {
        return Err(Error::DistributionAlreadyInitialized);
    }
    let initial_state = DistributionState {
        accumulator: 0,
        total_distributed: 0,
        total_staked: 0,
        last_update: env.ledger().timestamp(),
    };
    env.storage()
        .instance()
        .set(&DataKey::DistributionConfig, &token);
    save_state(env, &initial_state);
    Ok(())
}

/// Distribute `amount` of yield tokens to stakers. Admin only.
///
/// This records the accrual only; it moves no tokens. The float that claims are
/// paid from must already be in the contract. The accumulator is updated so
/// that each staked token's share of the distribution is immediately claimable.
///
/// Returns the new accumulator value.
pub fn distribute_yield(env: &Env, amount: i128) -> Result<i128, Error> {
    if amount <= 0 {
        return Err(Error::NothingToDistribute);
    }

    let token_addr = config_token(env)?;
    let mut current_state = state(env)?;

    // Only update the accumulator when tokens are actually staked. With no
    // stakers there is nobody to attribute the yield to, so it stays in the
    // contract and the next distribution is the first one the accumulator
    // prices.
    if current_state.total_staked > 0 {
        let increase =
            amount.checked_mul(PRECISION).ok_or(Error::MathOverflow)? / current_state.total_staked;
        current_state.accumulator = current_state
            .accumulator
            .checked_add(increase)
            .ok_or(Error::MathOverflow)?;
    }

    current_state.total_distributed = current_state
        .total_distributed
        .checked_add(amount)
        .ok_or(Error::MathOverflow)?;
    current_state.last_update = env.ledger().timestamp();
    save_state(env, &current_state);

    YieldDistributedEvent {
        token: token_addr,
        amount,
        accumulator: current_state.accumulator,
        total_staked: current_state.total_staked,
    }
    .publish(env);

    Ok(current_state.accumulator)
}

// ── User entry-point bodies ────────────────────────────────────────────────

/// Stake `amount` of the treasury's holding token to earn yield. Requires the
/// caller's authorization.
///
/// Yield accrued against the previous stake is settled first, then the
/// checkpoint is refreshed to the current accumulator, so the user earns from
/// the moment of this stake without losing anything already earned.
pub fn stake(env: &Env, user: &Address, amount: i128) -> Result<(), Error> {
    if amount <= 0 {
        return Err(Error::NothingToStake);
    }

    // `state` carries the initialization guard: nothing may be staked into a
    // distribution that has not been configured yet.
    let current_state = state(env)?;
    let token_addr = holding_token(env)?;

    let mut user_dist = user_distribution(env, user).unwrap_or(UserDistribution {
        staked: 0,
        checkpoint: current_state.accumulator,
        claimed: 0,
        pending: 0,
    });

    settle(&mut user_dist, &current_state)?;
    user_dist.staked = user_dist
        .staked
        .checked_add(amount)
        .ok_or(Error::MathOverflow)?;

    let client = token::Client::new(env, &token_addr);
    client.transfer(user, env.current_contract_address(), &amount);

    let mut new_state = current_state;
    new_state.total_staked = new_state
        .total_staked
        .checked_add(amount)
        .ok_or(Error::MathOverflow)?;
    save_state(env, &new_state);
    save_user_distribution(env, user, &user_dist);

    StakedEvent {
        user: user.clone(),
        amount,
        total_staked: new_state.total_staked,
    }
    .publish(env);

    Ok(())
}

/// Unstake `amount` of holding tokens. Requires the caller's authorization.
///
/// The user's checkpoint is refreshed to the current accumulator, so any
/// pending yield up to this point is preserved (but not auto-claimed — the
/// user must call [`claim_yield`] separately).
pub fn unstake(env: &Env, user: &Address, amount: i128) -> Result<(), Error> {
    if amount <= 0 {
        return Err(Error::NothingToUnstake);
    }

    let current_state = state(env)?;
    let token_addr = holding_token(env)?;

    let mut user_dist = user_distribution(env, user).ok_or(Error::NothingToUnstake)?;
    if amount > user_dist.staked {
        return Err(Error::UnstakeExceedsStaked);
    }

    settle(&mut user_dist, &current_state)?;
    user_dist.staked = user_dist
        .staked
        .checked_sub(amount)
        .ok_or(Error::MathOverflow)?;

    let client = token::Client::new(env, &token_addr);
    client.transfer(&env.current_contract_address(), user, &amount);

    let mut new_state = current_state;
    new_state.total_staked = new_state
        .total_staked
        .checked_sub(amount)
        .ok_or(Error::MathOverflow)?;
    save_state(env, &new_state);
    save_user_distribution(env, user, &user_dist);

    UnstakedEvent {
        user: user.clone(),
        amount,
        total_staked: new_state.total_staked,
    }
    .publish(env);

    Ok(())
}

/// Claim accumulated yield. Requires the caller's authorization.
///
/// Transfers all pending yield to the user and updates their checkpoint.
/// Returns the amount claimed.
pub fn claim_yield(env: &Env, user: &Address) -> Result<i128, Error> {
    let token_addr = config_token(env)?;
    let current_state = state(env)?;

    let mut user_dist = user_distribution(env, user).unwrap_or(UserDistribution {
        staked: 0,
        checkpoint: current_state.accumulator,
        claimed: 0,
        pending: 0,
    });

    settle(&mut user_dist, &current_state)?;
    let amount = user_dist.pending;
    if amount <= 0 {
        return Err(Error::NoYieldToClaim);
    }
    user_dist.pending = 0;

    user_dist.claimed = user_dist
        .claimed
        .checked_add(amount)
        .ok_or(Error::MathOverflow)?;
    save_user_distribution(env, user, &user_dist);

    let client = token::Client::new(env, &token_addr);
    client.transfer(&env.current_contract_address(), user, &amount);

    YieldClaimedEvent {
        user: user.clone(),
        amount,
        total_claimed: user_dist.claimed,
    }
    .publish(env);

    Ok(amount)
}

// ── Read-only ──────────────────────────────────────────────────────────────

/// Read-only: pending yield for `user`, in yield-token smallest units.
///
/// The settled bucket plus whatever has accrued against the current stake.
pub fn pending_yield(env: &Env, user: &Address) -> Result<i128, Error> {
    let current_state = state(env)?;
    let user_dist = user_distribution(env, user).unwrap_or(UserDistribution {
        staked: 0,
        checkpoint: current_state.accumulator,
        claimed: 0,
        pending: 0,
    });
    claimable(&current_state, &user_dist)
}

/// Read-only: the current global accumulator value.
pub fn accumulator(env: &Env) -> Result<i128, Error> {
    Ok(state(env)?.accumulator)
}

/// Read-only: the global distribution state.
pub fn distribution_state(env: &Env) -> Result<DistributionState, Error> {
    state(env)
}

/// Read-only: a user's distribution state, if they have one.
pub fn get_user_distribution(env: &Env, user: &Address) -> Option<UserDistribution> {
    user_distribution(env, user)
}
